[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2018"
name = "skia-rs"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
cssparser = "0.28"
napi = "1.0.0-alpha.1"
napi-derive = "1.0.0-alpha.0"
thiserror = "1"

[build-dependencies]
cc = "1"
napi-build = "1.0.0-alpha.0"

[profile.release]
lto = true
opt-level = 3
