[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2018"
name = "skia-rs"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
cssparser = "0.27"
napi = {git = "https://github.com/napi-rs/napi-rs"}
napi-derive = {git = "https://github.com/napi-rs/napi-rs"}
thiserror = "1"

[target.'cfg(all(unix, not(target_env = "musl")))'.dependencies]
jemallocator = {version = "0.3", features = ["disable_initial_exec_tls"]}

[build-dependencies]
cc = "1"
napi-build = {git = "https://github.com/napi-rs/napi-rs"}

[profile.release]
lto = true
opt-level = 3
