[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2018"
name = "skia-rs"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
cssparser = "0.28"
napi = "1.0.0-alpha.9"
napi-derive = "1.0.0-alpha.0"
thiserror = "1"

[target.'cfg(all(unix, not(target_env = "musl"), not(target_arch = "aarch64")))'.dependencies]
jemallocator = {version = "0.3", features = ["disable_initial_exec_tls"]}

[build-dependencies]
cc = "1"
napi-build = "1.0.0-alpha.0"

[profile.release]
codegen-units = 1
opt-level = 3
