name: Cargo test

env:
  DEBUG: 'napi:*'
  APP_NAME: 'skia'

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: stable - macOS - cargo - test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true

      - name: Generate Cargo.lock
        uses: actions-rs/cargo@v1
        with:
          command: generate-lockfile

      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: macOS-latest-cargo-test-node@14-cargo-registry-trimmed-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/git
          key: macOS-latest-cargo-test-node@14-cargo-index-trimmed-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache pnpm store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: npm-cache-test-linux-x64-gnu-${{ matrix.node }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Setup pnpm
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile

      - name: Install nasm
        run: brew install nasm

      - name: Download skia binary
        run: node ./scripts/release-skia-binary.js --download

      - name: Test
        run: cargo test -- --nocapture
