name: Cargo test

env:
  DEBUG: 'napi:*'
  APP_NAME: 'skia'

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: stable - macOS - cargo - test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: macOS-latest-test-cargo-cache

      - name: Cache yarn
        uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: bench-yarn-cache-node-16

      - name: Install dependencies
        run: yarn install --immutable --mode=skip-build

      - name: Install nasm
        run: brew install nasm

      - name: Download skia binary
        run: node ./scripts/release-skia-binary.js --download

      - name: Test
        run: cargo test -- --nocapture
