name: Build skia

on:
  push:
    branches:
      - release
    tags-ignore:
      - '**'
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip skia')"

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: stable - ${{ matrix.os }} - build skia
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          check-latest: true

      - uses: actions/setup-python@v3
        with:
          python-version: '2.x'
          architecture: 'x64'

      - name: Set env
        run: echo "${PWD}/depot_tools" >> $GITHUB_PATH
        shell: bash

      - name: Install tools on macOS
        run: brew install ninja
        if: matrix.os == 'macos-latest'

      - name: Install tools on Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install llvm ninja -y
          pip install certifi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_CONTAINER_UNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Compile skia
        if: matrix.os == 'ubuntu-latest'
        run: |
          docker pull ghcr.io/brooooooklyn/canvas/debian-builder:stretch
          docker tag ghcr.io/brooooooklyn/canvas/debian-builder:stretch builder
          docker run --user "$(id -u):$(id -g)" --rm -v $(pwd):/canvas -w /canvas builder node ./scripts/build-skia.js
        env:
          PYTHONHTTPSVERIFY: 0

      - name: Compile skia
        if: matrix.os == 'macos-latest'
        env:
          PYTHONHTTPSVERIFY: 0
        run: |
          node ./scripts/build-skia.js

      - name: Compile skia
        shell: powershell
        if: matrix.os == 'windows-latest'
        env:
          PYTHONHTTPSVERIFY: 0
        run: node ./scripts/build-skia.js

      - name: Cache pnpm store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: npm-cache-build-skia-${{ matrix.os }}-${{ matrix.node }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Setup pnpm
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile --ignore-scripts

      - name: Upload release
        run: node ./scripts/release-skia-binary.js --upload
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-apple-silicon:
    if: "!contains(github.event.head_commit.message, 'skip skia')"

    name: stable - apple-silicon - build skia
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          check-latest: true

      - uses: actions/setup-python@v3
        with:
          python-version: '2.x'
          architecture: 'x64'

      - name: Set env
        run: echo "${PWD}/depot_tools" >> $GITHUB_PATH
        shell: bash

      - name: Install tools on macOS
        run: brew install ninja

      - name: Compile skia
        run: node ./scripts/build-skia.js --target=aarch64-apple-darwin

      - name: Cache pnpm store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: npm-cache-build-skia-darwin-aarch64-${{ matrix.node }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Setup pnpm
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile --ignore-scripts

      - name: Upload release
        run: node ./scripts/release-skia-binary.js --upload --target=aarch64-apple-darwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-x64-linux-musl:
    if: "!contains(github.event.head_commit.message, 'skip skia')"

    name: stable - linux-x64-musl - build skia
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          check-latest: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_CONTAINER_UNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Compile skia
        run: |
          docker pull ghcr.io/brooooooklyn/canvas/musl-builder:lts
          docker tag ghcr.io/brooooooklyn/canvas/musl-builder:lts builder
          docker run --user "$(id -u):$(id -g)" --rm -v $(pwd):/canvas -w /canvas builder node ./scripts/build-skia.js
        env:
          PYTHONHTTPSVERIFY: 0

      - name: Cache pnpm store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: npm-cache-build-skia-linux-x64-musl-${{ matrix.node }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Setup pnpm
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile --ignore-scripts

      - name: Upload release
        run: node ./scripts/release-skia-binary.js --upload --target=x86_64-unknown-linux-musl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-aarch64-linux-gnu:
    if: "!contains(github.event.head_commit.message, 'skip skia')"

    name: stable - aarch64-linux - build skia
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          check-latest: true

      - uses: actions/setup-python@v3
        with:
          python-version: '2.x'
          architecture: 'x64'

      - name: Set env
        run: echo "${PWD}/depot_tools" >> $GITHUB_PATH
        shell: bash

      - name: Install cross compile tools
        run: |
          sudo apt-get update
          sudo apt-get install g++-10-aarch64-linux-gnu gcc-10-aarch64-linux-gnu -y

      - name: Compile skia
        run: node ./scripts/build-skia.js --target=aarch64-unknown-linux-gnu

      - name: Cache pnpm store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: npm-cache-build-skia-linux-aarch64-gnu-${{ matrix.node }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Setup pnpm
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile --ignore-scripts

      - name: Upload release
        run: node ./scripts/release-skia-binary.js --upload --target=aarch64-unknown-linux-gnu
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-aarch64-linux-musl:
    if: "!contains(github.event.head_commit.message, 'skip skia')"

    name: stable - linux-x64-musl - build skia
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          check-latest: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_CONTAINER_UNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Compile skia
        run: |
          docker pull ghcr.io/brooooooklyn/canvas/musl-builder:lts
          docker tag ghcr.io/brooooooklyn/canvas/musl-builder:lts builder
          docker run --user "$(id -u):$(id -g)" --rm -v $(pwd):/canvas -w /canvas builder node ./scripts/build-skia.js --target=aarch64-unknown-linux-musl
        env:
          PYTHONHTTPSVERIFY: 0

      - name: Cache pnpm store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: npm-cache-build-skia-linux-aarch64-musl-${{ matrix.node }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Setup pnpm
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile --ignore-scripts

      - name: Upload release
        run: node ./scripts/release-skia-binary.js --upload --target=aarch64-unknown-linux-musl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-armv7-linux-gnu:
    if: "!contains(github.event.head_commit.message, 'skip skia')"

    name: stable - armv7-linux - build skia
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          check-latest: true

      - uses: actions/setup-python@v3
        with:
          python-version: '2.x'
          architecture: 'x64'

      - name: Set env
        run: echo "${PWD}/depot_tools" >> $GITHUB_PATH
        shell: bash

      - name: Install cross compile tools
        run: |
          sudo apt-get update
          sudo apt-get install gcc-10-arm-linux-gnueabihf g++-10-arm-linux-gnueabihf -y

      - name: Compile skia
        run: node ./scripts/build-skia.js --target=armv7-unknown-linux-gnueabihf

      - name: Cache pnpm store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: npm-cache-build-skia-linux-armv7-gnu-${{ matrix.node }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Setup pnpm
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile --ignore-scripts

      - name: Upload release
        run: node ./scripts/release-skia-binary.js --upload --target=armv7-unknown-linux-gnueabihf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-aarch64-linux-android:
    if: "!contains(github.event.head_commit.message, 'skip skia')"

    name: stable - aarch64-linux-android - build skia
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          check-latest: true

      - uses: actions/setup-python@v3
        with:
          python-version: '2.x'
          architecture: 'x64'

      - name: Set env
        run: echo "${PWD}/depot_tools" >> $GITHUB_PATH
        shell: bash

      - name: Compile skia
        run: node ./scripts/build-skia.js --target=aarch64-linux-android

      - name: Cache pnpm store
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: npm-cache-build-skia-android-aarch64-${{ matrix.node }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Setup pnpm
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile --ignore-scripts

      - name: Upload release
        run: node ./scripts/release-skia-binary.js --upload --target=aarch64-linux-android
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
